document.write('<script src="app-core.js"><\/script><script src="default-albums-migration.js"><\/script><script src="numismatic-core.js"><\/script><script src="chronology-guard.js"><\/script><script src="verified-knowledge-core.js"><\/script><script src="verified-catalog-bridge.js"><\/script><script src="auction-archive-core.js"><\/script><script src="multi-source-knowledge-core.js"><\/script><script src="open-knowledge-import.js"><\/script><script src="coin-fingerprint-core.js"><\/script><script src="quality-learning-core.js"><\/script><script src="stage2-fingerprint-match.js"><\/script><script src="analysis-reference-check.js"><\/script><script src="community-knowledge-core.js"><\/script><script src="analysis-quality-ui.js"><\/script><script src="analysis-owner-measurements.js"><\/script><script src="market-valuation-hook.js"><\/script><script src="analysis-numismatic-market.js"><\/script><script src="wcn-batch-import.js"><\/script><script src="auction-alerts-core.js"><\/script><script src="auction-actions-core.js"><\/script><script src="auction-context-navigation.js"><\/script><script src="export-privacy-core.js"><\/script><script src="zip-store.js"><\/script><script src="xlsx-sheet.js"><\/script><script src="xlsx-package.js"><\/script><script src="i18n-hotfix.js"><\/script><script src="i18n-extra.js"><\/script><script src="i18n-pretest.js"><\/script><script src="home-i18n.js"><\/script><script src="home-dashboard-summary.js"><\/script><script src="runtime-fixes.js"><\/script><script src="user-albums-ui.js"><\/script><script src="collection-extra-filters.js"><\/script><script src="analysis-unified-upload.js"><\/script><script src="analysis-image-session-fix.js"><\/script><script src="analysis-state-guard.js"><\/script><script src="analysis-content-i18n.js"><\/script><script src="analysis-inline-correction.js"><\/script><script src="album-photo-prep.js"><\/script><script src="analysis-album-save-fix.js"><\/script><script src="analysis-record-flow-fix.js"><\/script><script src="coin-card-finish.js"><\/script><script src="catalog-check-hook.js"><\/script><script src="correction-consistency.js"><\/script><script src="derived-analysis-invalidation.js"><\/script><script src="i18n-complete.js"><\/script><script src="i18n-complete-extra.js"><\/script><script src="i18n-photo-prep.js"><\/script><script src="i18n-market-valuation.js"><\/script><script src="i18n-fingerprint.js"><\/script><script src="i18n-new-ui.js"><\/script>');
document.write('<script src="analysis-image-pipeline.js"><\/script>');
document.write('<script src="collection-content-i18n.js"><\/script>');
document.write('<script src="album-demo-i18n.js"><\/script>');
document.write('<script src="album-navigation-hotfix.js"><\/script>');
document.write('<script src="auction-house-live.js"><\/script>');
document.write('<script src="calendar-target-hotfix.js"><\/script>');
document.write('<script src="pretester-stability-fix.js"><\/script>');
addEventListener('DOMContentLoaded',()=>{if(!location.pathname.endsWith('coin-edit.html'))return;let s;try{s=JSON.parse(sessionStorage.getItem('apomonetAnalysisSession')||'null')}catch{}const q=new URLSearchParams(location.search),coinId=q.get('id');if(!s?.a||!s?.id||!coinId||s.id!==coinId)return;for(const k of ['title','nominal','ruler','year','metal','mint','variant','grade','rarity']){const e=document.getElementById(k);if(e&&!e.value&&s.a[k]!=null)e.value=s.a[k]}});
addEventListener('DOMContentLoaded',()=>{let answers=[];try{answers=JSON.parse(sessionStorage.getItem('apomonetOwnerAnswers')||'[]')}catch{}if(window.ApoMonet&&answers.length){const old=window.ApoMonet.upsertCoin;window.ApoMonet.upsertCoin=c=>old({...c,userAdditionalInfo:c.userAdditionalInfo||answers})}});
addEventListener('DOMContentLoaded',()=>{if(!location.pathname.endsWith('analyze.html')||sessionStorage.getItem('apomonetOpenAlbumAfterResume')!=='1')return;sessionStorage.removeItem('apomonetOpenAlbumAfterResume');let tries=0;const t=setInterval(()=>{tries++;const b=document.getElementById('album'),panel=document.getElementById('panel');if(b&&panel&&!panel.classList.contains('hidden')){clearInterval(t);b.click()}else if(tries>20)clearInterval(t)},100)});
// deployment-sync: quality + measurements + dashboard + filters + inline correction + translations + demo album navigation + contextual auction links + fresh-record navigation guard + catalog rarity + correction-derived invalidation + pretester stability
