(()=>{const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const eras=[
{id:'medieval',name:'Średniowiecze',from:960,to:1506},{id:'jagiellonian',name:'Jagiellonowie',from:1386,to:1572},{id:'elective',name:'Rzeczpospolita Obojga Narodów',from:1573,to:1795},{id:'partitions',name:'Zabory i XIX wiek',from:1795,to:1918},{id:'ii-rp',name:'II Rzeczpospolita',from:1918,to:1939},{id:'war',name:'Okres wojenny',from:1939,to:1945},{id:'prl',name:'PRL',from:1945,to:1989},{id:'iii-rp',name:'III Rzeczpospolita',from:1990,to:2100}];
const rulers=[
{id:'mieszko-i',name:'Mieszko I',from:960,to:992,era:'medieval'},{id:'chrobry',name:'Bolesław I Chrobry',from:992,to:1025,era:'medieval'},{id:'kazimierz-wielki',name:'Kazimierz III Wielki',from:1333,to:1370,era:'medieval'},{id:'jagiello',name:'Władysław II Jagiełło',from:1386,to:1434,era:'jagiellonian'},{id:'zygmunt-stary',name:'Zygmunt I Stary',from:1506,to:1548,era:'jagiellonian'},{id:'zygmunt-august',name:'Zygmunt II August',from:1548,to:1572,era:'jagiellonian'},{id:'batory',name:'Stefan Batory',from:1576,to:1586,era:'elective'},{id:'zygmunt-iii',name:'Zygmunt III Waza',from:1587,to:1632,era:'elective'},{id:'wladyslaw-iv',name:'Władysław IV Waza',from:1632,to:1648,era:'elective'},{id:'jan-kazimierz',name:'Jan II Kazimierz',from:1648,to:1668,era:'elective'},{id:'sobieski',name:'Jan III Sobieski',from:1674,to:1696,era:'elective'},{id:'stanislaw-august',name:'Stanisław August Poniatowski',from:1764,to:1795,era:'elective'}];
const denominations=['denar','brakteat','kwartnik','półgrosz','grosz','trojak','szóstak','ort','półtalar','talar','dwutalar','dukat','półdukat','dwudukat','złoty','fenig','grosz gdański','gulden','marka','złotych'];
const mints=['Kraków','Poznań','Wschowa','Bydgoszcz','Malbork','Elbląg','Gdańsk','Toruń','Wilno','Ryga','Warszawa','Utrecht','Berlin'];
function yearOf(v){const m=String(v||'').match(/\b(9\d{2}|1\d{3}|20\d{2})\b/);return m?Number(m[1]):null}
function rulerForYear(y){return y?rulers.filter(r=>y>=r.from&&y<=r.to):[]}
function eraForYear(y){return y?eras.find(e=>y>=e.from&&y<=e.to)||null:null}
function denominationMatches(text){const n=norm(text);return denominations.filter(d=>n.includes(norm(d))).sort((a,b)=>b.length-a.length)}
function validate(a={}){const y=yearOf(a.year),possible=rulerForYear(y),warnings=[];if(y&&a.ruler&&norm(a.ruler)!=='nie ustalono'&&possible.length&&!possible.some(r=>norm(a.ruler).includes(norm(r.name))||norm(r.name).includes(norm(a.ruler))))warnings.push(`Władca „${a.ruler}” nie pasuje do roku ${y}. Sprawdź identyfikację.`);if(a.nominal&&!denominationMatches(a.nominal).length)warnings.push('Nominał nie znajduje się jeszcze w podstawowym słowniku APOMONET — wymaga potwierdzenia lub rozszerzenia katalogu.');return{year:y,era:eraForYear(y),possibleRulers:possible,warnings}}
function score(candidate,a={}){let s=0;if(candidate.year&&yearOf(a.year)===candidate.year)s+=45;if(candidate.ruler&&norm(a.ruler).includes(norm(candidate.ruler)))s+=20;if(candidate.nominal&&norm(a.nominal).includes(norm(candidate.nominal)))s+=20;if(candidate.mint&&norm(a.mint).includes(norm(candidate.mint)))s+=10;if(candidate.metal&&norm(a.metal).includes(norm(candidate.metal)))s+=5;return s}
const types=[];function registerTypes(rows){for(const r of rows||[])if(r&&r.id&&!types.some(x=>x.id===r.id))types.push({...r})}
function suggest(a,limit=8){return types.map(t=>({...t,matchScore:score(t,a)})).filter(x=>x.matchScore>0).sort((x,y)=>y.matchScore-x.matchScore).slice(0,limit)}
function sameVariant(c,a){return !!(c&&a&&norm(c.ruler)===norm(a.ruler)&&norm(c.year)===norm(a.year)&&norm(c.nominal)===norm(a.nominal)&&norm(c.mint)===norm(a.mint)&&norm(c.variant)===norm(a.variant))}
window.ApoNumis={eras,rulers,denominations,mints,types,registerTypes,yearOf,rulerForYear,eraForYear,denominationMatches,validate,suggest,sameVariant,normalize:norm};})();