(()=>{const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l').replace(/đ/g,'d').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim();
const eras=[
{id:'medieval',name:'Średniowiecze',from:960,to:1506},{id:'jagiellonian',name:'Jagiellonowie',from:1386,to:1572},{id:'elective',name:'Rzeczpospolita Obojga Narodów',from:1573,to:1795},{id:'partitions',name:'Zabory i XIX wiek',from:1795,to:1918},{id:'ii-rp',name:'II Rzeczpospolita',from:1918,to:1939},{id:'war',name:'Okres wojenny',from:1939,to:1945},{id:'prl',name:'PRL',from:1945,to:1989},{id:'iii-rp',name:'III Rzeczpospolita',from:1990,to:2100}];
const rulers=[
{id:'mieszko-i',name:'Mieszko I',from:960,to:992,era:'medieval'},{id:'chrobry',name:'Bolesław I Chrobry',from:992,to:1025,era:'medieval'},{id:'kazimierz-wielki',name:'Kazimierz III Wielki',from:1333,to:1370,era:'medieval'},{id:'jagiello',name:'Władysław II Jagiełło',from:1386,to:1434,era:'jagiellonian'},{id:'zygmunt-stary',name:'Zygmunt I Stary',from:1506,to:1548,era:'jagiellonian'},{id:'zygmunt-august',name:'Zygmunt II August',from:1548,to:1572,era:'jagiellonian'},{id:'henryk-walezy',name:'Henryk Walezy',from:1573,to:1575,era:'elective'},{id:'anna-jagiellonka',name:'Anna Jagiellonka',from:1575,to:1586,era:'elective'},{id:'batory',name:'Stefan Batory',from:1576,to:1586,era:'elective'},{id:'zygmunt-iii',name:'Zygmunt III Waza',from:1587,to:1632,era:'elective'},{id:'wladyslaw-iv',name:'Władysław IV Waza',from:1632,to:1648,era:'elective'},{id:'jan-kazimierz',name:'Jan II Kazimierz',from:1648,to:1668,era:'elective'},{id:'michal-korybut',name:'Michał Korybut Wiśniowiecki',from:1669,to:1673,era:'elective'},{id:'sobieski',name:'Jan III Sobieski',from:1674,to:1696,era:'elective'},{id:'august-ii-1',name:'August II Mocny',from:1697,to:1706,era:'elective'},{id:'leszczynski-1',name:'Stanisław Leszczyński',from:1704,to:1709,era:'elective'},{id:'august-ii-2',name:'August II Mocny',from:1709,to:1733,era:'elective'},{id:'leszczynski-2',name:'Stanisław Leszczyński',from:1733,to:1736,era:'elective'},{id:'august-iii',name:'August III Sas',from:1733,to:1763,era:'elective'},{id:'stanislaw-august',name:'Stanisław August Poniatowski',from:1764,to:1795,era:'elective'}];
const denominations=['Denar','Brakteat','Kwartnik','Półgrosz','Grosz','Półtorak','Trojak','Szóstak','Ort','Półtalar','Talar','Dwutalar','Dukat','Półdukat','Dwudukat','Złoty','Fenig','Grosz gdański','Gulden','Marka','Złotych'];
const denominationAliases=new Map([
['poltalar','Półtalar'],['pol talar','Półtalar'],['pultalar','Półtalar'],['1 2 talar','Półtalar'],
['poldukat','Półdukat'],['pol dukat','Półdukat'],['1 2 dukat','Półdukat'],
['polgrosz','Półgrosz'],['pol grosz','Półgrosz'],['1 2 grosz','Półgrosz'],
['poltorak','Półtorak'],['pol torak','Półtorak'],['szostak','Szóstak'],['zloty','Złoty'],
['dwutalar','Dwutalar'],['dwa talary','Dwutalar'],['2 talary','Dwutalar'],
['dwudukat','Dwudukat'],['dwa dukaty','Dwudukat'],['2 dukaty','Dwudukat']
]);
const mints=['Kraków','Poznań','Wschowa','Bydgoszcz','Malbork','Elbląg','Gdańsk','Toruń','Wilno','Ryga','Warszawa','Utrecht','Berlin'];
function yearOf(v){const m=String(v||'').match(/\b(9\d{2}|1\d{3}|20\d{2})\b/);return m?Number(m[1]):null}
function rulerForYear(y){return y?rulers.filter(r=>y>=r.from&&y<=r.to):[]}
function eraForYear(y){return y?eras.find(e=>y>=e.from&&y<=e.to)||null:null}
function denominationMatches(text){const n=norm(text);return denominations.filter(d=>n.includes(norm(d))).sort((a,b)=>b.length-a.length)}
function canonicalDenomination(value){const raw=String(value||'').trim();if(!raw)return'';const normalized=norm(raw);const alias=denominationAliases.get(normalized);if(alias)return alias;const exact=denominations.find(item=>norm(item)===normalized);return exact||raw}
function denominationSuggestions(value,limit=6){const normalized=norm(value);if(!normalized)return denominations.slice(0,limit);const ranked=denominations.map(item=>{const candidate=norm(item);let score=0;if(candidate===normalized)score=100;else if(candidate.startsWith(normalized)||normalized.startsWith(candidate))score=80;else if(candidate.includes(normalized)||normalized.includes(candidate))score=60;return{item,score}}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||a.item.localeCompare(b.item,'pl')).slice(0,limit).map(row=>row.item);const alias=denominationAliases.get(normalized);return alias?[alias,...ranked.filter(item=>item!==alias)].slice(0,limit):ranked}
function validate(a={}){const y=yearOf(a.year),possible=rulerForYear(y),warnings=[];if(y&&a.ruler&&norm(a.ruler)!=='nie ustalono'&&possible.length&&!possible.some(r=>norm(a.ruler).includes(norm(r.name))||norm(r.name).includes(norm(a.ruler))))warnings.push(`Władca „${a.ruler}” nie pasuje do roku ${y}. Sprawdź identyfikację.`);if(a.nominal&&!denominationMatches(a.nominal).length)warnings.push('Nominał nie znajduje się jeszcze w podstawowym słowniku APOMONET — wymaga potwierdzenia lub rozszerzenia katalogu.');return{year:y,era:eraForYear(y),possibleRulers:possible,warnings}}
function score(candidate,a={}){let s=0;if(candidate.year&&yearOf(a.year)===candidate.year)s+=45;if(candidate.ruler&&norm(a.ruler).includes(norm(candidate.ruler)))s+=20;if(candidate.nominal&&norm(a.nominal).includes(norm(candidate.nominal)))s+=20;if(candidate.mint&&norm(a.mint).includes(norm(candidate.mint)))s+=10;if(candidate.metal&&norm(a.metal).includes(norm(candidate.metal)))s+=5;return s}
const types=[];function registerTypes(rows){for(const r of rows||[])if(r&&r.id&&!types.some(x=>x.id===r.id))types.push({...r})}
function suggest(a,limit=8){return types.map(t=>({...t,matchScore:score(t,a)})).filter(x=>x.matchScore>0).sort((x,y)=>y.matchScore-x.matchScore).slice(0,limit)}
function sameVariant(c,a){return !!(c&&a&&norm(c.ruler)===norm(a.ruler)&&norm(c.year)===norm(a.year)&&norm(c.nominal)===norm(a.nominal)&&norm(c.mint)===norm(a.mint)&&norm(c.variant)===norm(a.variant))}
window.ApoNumis={eras,rulers,denominations,mints,types,registerTypes,yearOf,rulerForYear,eraForYear,denominationMatches,canonicalDenomination,denominationSuggestions,validate,suggest,sameVariant,normalize:norm};})();
