export default async function handler(req,res){
 if(req.method!=="POST") return res.status(405).json({error:"Dozwolona jest tylko metoda POST."});
 try{
  const apiKey=process.env.OPENAI_API_KEY?.trim(); if(!apiKey) return res.status(500).json({error:"Brak OPENAI_API_KEY na aktywnym deploymentcie."});
  const b=req.body||{}, images=Array.isArray(b.images)?b.images.filter(Boolean):[]; if(images.length<2) return res.status(400).json({error:"Potrzebne są dwa zdjęcia."});
  const base=b.base||{};
  const content=[{type:"input_text",text:`Jesteś ekspertem numizmatycznym. To DRUGI, opcjonalny etap analizy. Dane bazowe zostały wcześniej rozpoznane i użytkownik mógł je poprawić. Traktuj je jako punkt odniesienia, ale zgłoś sprzeczność, jeśli obraz jednoznacznie jej dowodzi.\nDane bazowe: ${JSON.stringify(base)}\n\nPrzeprowadź analizę odmianową: dokładna interpunkcja i układ legend, kształty liter/cyfr, korona, herb/tarcza, monogramy, znaki mennicze, liczba i układ piór/skrzydeł oraz inne diagnostyczne szczegóły stempla. Spróbuj wskazać odmianę oraz Kopickiego i rzadkość WYŁĄCZNIE jeśli masz wiarygodne podstawy. Nie wymyślaj katalogu. Opisz, które cechy przesądziły o wariancie. Odpowiadaj po polsku.`},{type:"input_image",image_url:images[0],detail:"high"},{type:"input_image",image_url:images[1],detail:"high"}];
  const schema={type:"object",additionalProperties:false,properties:{variant:{type:"string"},kopickiReference:{type:"string"},kopickiRarity:{type:"string"},obverseDetails:{type:"string"},reverseDetails:{type:"string"},legendPunctuation:{type:"string"},diagnosticFeatures:{type:"array",items:{type:"string"}},fullDescription:{type:"string"},confidence:{type:"integer",minimum:0,maximum:100},warnings:{type:"array",items:{type:"string"}}},required:["variant","kopickiReference","kopickiRarity","obverseDetails","reverseDetails","legendPunctuation","diagnosticFeatures","fullDescription","confidence","warnings"]};
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-5.6",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"coin_detail",strict:true,schema}}})});
  const data=await r.json(); if(!r.ok) return res.status(r.status).json({error:data?.error?.message||"Błąd analizy szczegółowej."});
  let t=data.output_text||""; if(!t&&Array.isArray(data.output)) for(const i of data.output) if(i.type==="message") for(const p of i.content||[]) if(p.type==="output_text") t+=p.text||"";
  return res.status(200).json({success:true,detail:JSON.parse(t)});
 }catch(e){console.error(e);return res.status(500).json({error:e?.message||"Błąd analizy szczegółowej."});}
}