export default async function handler(req,res){
 if(req.method!=="POST")return res.status(405).json({error:"Dozwolona jest tylko metoda POST."});
 res.setHeader('Cache-Control','no-store, max-age=0');
 try{
  const key=process.env.OPENAI_API_KEY?.trim();if(!key)return res.status(500).json({error:"Brak OPENAI_API_KEY na aktywnym deploymentcie."});
  const b=req.body||{},im=Array.isArray(b.images)?b.images.filter(Boolean):[];
  if(im.length<2)return res.status(400).json({error:"Potrzebne są dwa zdjęcia."});
  if(im.some(x=>typeof x!=='string'||x.length>1800000))return res.status(413).json({error:"Zdjęcia są zbyt duże do stabilnej analizy. Wczytaj je ponownie — APOMONET zmniejszy je automatycznie."});
  const prompt=`ETAP 1 — SZYBKA identyfikacja numizmatyczna. Najpierw oceń, czy OBA zdjęcia nadają się do wiarygodnej identyfikacji. Ustaw imageUsable=false, jeśli moneta jest mocno rozmazana, poważnie ucięta, zbyt mała, prześwietlona, zasłonięta, oba zdjęcia pokazują tę samą stronę albo szczegóły są zbyt słabe do podstawowej identyfikacji.\n\nRozpoznawaj NIEZALEŻNIE: (1) widoczną datę cyfra po cyfrze, (2) legendę awersu, (3) legendę rewersu, (4) władcę/emitenta wynikającego z portretu i legendy, (5) nominał wynikający z całego typu monety. Nie pozwól, aby jedna z tych rzeczy wymusiła pozostałe.\n\nDATA: dateDigits ma mieć 4 znaki; jeśli cyfry nie widzisz pewnie, wpisz ?. dateDigitConfidence to pewność każdej cyfry wyłącznie z obrazu. Nie rekonstruuj brakującej cyfry z historii.\n\nWŁADCA: portraitRuler i portraitConfidence dotyczą samego portretu/heraldyki, ruler jest oceną łączną z legendą. Przepisz czytelne fragmenty legend. Nie utożsamiaj Zygmunta I Starego, Zygmunta II Augusta i Zygmunta III Wazy. Jeśli portret, legenda i data są sprzeczne, NIE naprawiaj wyniku wiedzą historyczną — zgłoś konflikt.\n\nNOMINAŁ: nominalConfidence i denominationEvidence mają wyjaśniać wybór. Dla półtalara/talara/dwutalara nie zgaduj po rozmiarze fotografii. Jeśli typ nie rozstrzyga, wpisz np. "talar / dwutalar — do potwierdzenia" i poproś o wagę oraz średnicę.\n\nNie wykonuj analizy odmianowej. Ustal kraj/emitenta, władcę, rok, nominał, metal, mennicę jeśli czytelna, ogólny typ i orientacyjny stan. Jeśli nie wiesz, wpisz Nie ustalono. Podaj ostrożny przedział wartości tylko przy wystarczająco pewnej identyfikacji. followUpQuestions maksymalnie 4. Confidence nigdy nie może wynosić 100%. Odpowiadaj po polsku.`;
  const content=[{type:"input_text",text:prompt},{type:"input_image",image_url:im[0],detail:"high"},{type:"input_image",image_url:im[1],detail:"high"}];
  const schema={type:"object",additionalProperties:false,properties:{imageUsable:{type:"boolean"},imageQualityNote:{type:"string"},title:{type:"string"},country:{type:"string"},ruler:{type:"string"},portraitRuler:{type:"string"},portraitConfidence:{type:"integer",minimum:0,maximum:100},obverseLegend:{type:"string"},reverseLegend:{type:"string"},year:{type:"string"},nominal:{type:"string"},nominalConfidence:{type:"integer",minimum:0,maximum:100},denominationEvidence:{type:"string"},metal:{type:"string"},mint:{type:"string"},variant:{type:"string"},grade:{type:"string"},visibleDateReading:{type:"string"},dateDigits:{type:"array",items:{type:"string"},minItems:4,maxItems:4},dateDigitConfidence:{type:"array",items:{type:"integer",minimum:0,maximum:100},minItems:4,maxItems:4},confidence:{type:"integer",minimum:0,maximum:95},rulerConfidence:{type:"integer",minimum:0,maximum:100},yearConfidence:{type:"integer",minimum:0,maximum:100},estimateLow:{type:"number",minimum:0},estimateHigh:{type:"number",minimum:0},valuationCurrency:{type:"string"},valuationNote:{type:"string"},followUpQuestions:{type:"array",maxItems:4,items:{type:"string"}},fullDescription:{type:"string"},warnings:{type:"array",items:{type:"string"}}},required:["imageUsable","imageQualityNote","title","country","ruler","portraitRuler","portraitConfidence","obverseLegend","reverseLegend","year","nominal","nominalConfidence","denominationEvidence","metal","mint","variant","grade","visibleDateReading","dateDigits","dateDigitConfidence","confidence","rulerConfidence","yearConfidence","estimateLow","estimateHigh","valuationCurrency","valuationNote","followUpQuestions","fullDescription","warnings"]};
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:"gpt-5.6",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"coin_basic_v3",strict:true,schema}}})});
  const d=await r.json();if(!r.ok)return res.status(r.status).json({error:d?.error?.message||"Błąd analizy."});
  let t=d.output_text||"";if(!t&&Array.isArray(d.output))for(const i of d.output)if(i.type==="message")for(const p of i.content||[])if(p.type==="output_text")t+=p.text||"";
  let a=JSON.parse(t);if(a.imageUsable===false)return res.status(422).json({error:a.imageQualityNote||"Zdjęcia są zbyt słabe do wiarygodnej analizy."});
  a.warnings=Array.isArray(a.warnings)?a.warnings:[];a.followUpQuestions=Array.isArray(a.followUpQuestions)?a.followUpQuestions:[];
  a.confidence=Math.min(95,Number(a.confidence||0));
  const ds=(a.dateDigits||[]).map(x=>String(x||'?').trim()),cs=a.dateDigitConfidence||[];
  const allDigits=ds.length===4&&ds.every(x=>/^\d$/.test(x)),veryStrong=allDigits&&cs.length===4&&cs.every(x=>Number(x)>=90);
  const visual=ds.length===4?ds.map((x,i)=>/^\d$/.test(x)&&Number(cs[i]||0)>=90?x:'?').join(''):'????';a.visibleDateReading=visual;
  if(veryStrong){a.year=ds.join('');a.yearConfidence=Math.min(100,Math.round(cs.reduce((s,x)=>s+Number(x||0),0)/4))}else{a.year=visual==='????'?'Nie ustalono':visual;a.yearConfidence=Math.min(Number(a.yearConfidence||0),69);a.confidence=Math.min(a.confidence,74);a.estimateLow=0;a.estimateHigh=0;a.valuationNote='Wycena wstrzymana: data nie została odczytana z wystarczającą pewnością wizualną.';a.warnings.push('Niepewnych cyfr daty nie uzupełniono z wiedzy historycznej.');if(!a.followUpQuestions.some(q=>/rok|data/i.test(q)))a.followUpQuestions.unshift('Potwierdź rok monety lub dodaj zbliżenie daty.')}
  const reigns=[['Zygmunt I Stary',1506,1548],['Zygmunt II August',1548,1572],['Henryk Walezy',1573,1575],['Anna Jagiellonka',1575,1596],['Stefan Batory',1576,1586],['Zygmunt III Waza',1587,1632],['Władysław IV Waza',1632,1648],['Jan II Kazimierz',1648,1668],['Michał Korybut Wiśniowiecki',1669,1673],['Jan III Sobieski',1674,1696],['August II Mocny',1697,1706],['Stanisław Leszczyński',1704,1709],['August II Mocny',1709,1733],['Stanisław Leszczyński',1733,1736],['August III Sas',1733,1763],['Stanisław August Poniatowski',1764,1795]];
  const n=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ł/g,'l');
  const y=veryStrong?Number(ds.join('')):null;
  if(y&&a.ruler&&n(a.ruler)!=='nie ustalono'){
    const possible=reigns.filter(x=>y>=x[1]&&y<=x[2]);
    if(possible.length&&!possible.some(x=>n(a.ruler).includes(n(x[0]))||n(x[0]).includes(n(a.ruler)))){
      a.warnings.push(`Konflikt chronologiczny: rok ${y} nie pasuje do rozpoznania „${a.ruler}”. APOMONET nie zmienił władcy automatycznie — sprawdź portret i legendę.`);
      a.confidence=Math.min(a.confidence,72);a.rulerConfidence=Math.min(Number(a.rulerConfidence||0),72);a.estimateLow=0;a.estimateHigh=0;a.valuationNote='Wycena wstrzymana: konflikt rok–władca wymaga ręcznej kontroli.';
      if(!a.followUpQuestions.some(q=>/wład|wlad|portret|legend/i.test(q)))a.followUpQuestions.unshift('Potwierdź władcę na podstawie portretu lub czytelnego fragmentu legendy.')
    }
  }
  const talarFamily=/talar/i.test(String(a.nominal||''));if(talarFamily&&Number(a.nominalConfidence||0)<90){a.confidence=Math.min(a.confidence,82);if(!a.followUpQuestions.some(q=>/wag|śred|sred/i.test(q)))a.followUpQuestions.unshift('Podaj wagę i średnicę monety — są potrzebne do pewnego rozróżnienia półtalara, talara i dwutalara.');a.estimateLow=0;a.estimateHigh=0;a.valuationNote='Wycena wstrzymana: nominał z rodziny talarowej wymaga potwierdzenia wagą/średnicą lub cechami typu.'}
  if(Number(a.portraitConfidence||0)<75&&Number(a.rulerConfidence||0)>85)a.rulerConfidence=85;if(Number(a.nominalConfidence||0)<75)a.confidence=Math.min(a.confidence,80);
  a.followUpQuestions=a.followUpQuestions.slice(0,4);if(!a.valuationCurrency)a.valuationCurrency='PLN';if(Number(a.estimateHigh)<Number(a.estimateLow)){const x=a.estimateLow;a.estimateLow=a.estimateHigh;a.estimateHigh=x}
  return res.status(200).json({success:true,analysis:a});
 }catch(e){console.error(e);return res.status(500).json({error:e?.message||"Wewnętrzny błąd APOMONET."})}
}
