export default async function handler(req,res){
 if(req.method!=="POST") return res.status(405).json({error:"Dozwolona jest tylko metoda POST."});
 try{
  const apiKey=process.env.OPENAI_API_KEY?.trim(); if(!apiKey) return res.status(500).json({error:"Brak OPENAI_API_KEY na aktywnym deploymentcie."});
  const b=req.body||{}, images=Array.isArray(b.images)?b.images.filter(Boolean):[]; if(images.length<2) return res.status(400).json({error:"Potrzebne są dwa zdjęcia."});
  const base=b.base||{};
  const content=[{type:"input_text",text:`Jesteś ekspertem numizmatycznym. To DRUGI, opcjonalny etap analizy APOMONET. Dane bazowe mogły zostać ręcznie poprawione przez właściciela. Pola zaakceptowane przez użytkownika są nadrzędnym punktem odniesienia. NIE wracaj automatycznie do wcześniejszego strzału AI.\n\nDane bazowe po korekcie: ${JSON.stringify(base)}\n\nNajpierw sprawdź zgodność obrazu z ruler/year/nominal/mint/metal. Jeśli widzisz jednoznaczną sprzeczność, NIE nadpisuj tych pól po cichu — dodaj ostrzeżenie. Następnie analizuj odmianę i stempel: interpunkcję, rozstaw daty, położenie daty, początek/koniec legendy w układzie zegarowym, formy liter i cyfr, orientację i proporcje portretu, koronę, herb/tarczę, monogramy, znaki mennicze, pióra/skrzydła/ogon orła, rant jeśli jest widoczny.\n\nZbuduj również fingerprint geometryczno-diagnostyczny. To NIE jest opis ani kopia zdjęcia. Każda cecha fingerprintu ma wartość tekstową, confidence 0-100 i method. Gdy cechy nie da się wiarygodnie zobaczyć, ustaw value na pusty tekst i confidence=0. NIE zgaduj mikroszczegółów. Pozycje zegarowe zapisuj np. '3:00', '11:30'; rozstaw/pozycję opisuj względnie i konsekwentnie (np. 'wąski', 'szeroki', 'blisko obrzeża', 'centralnie').\n\nPełny opis MUSI być napisany od nowa zgodnie z poprawionymi danymi bazowymi. Kopicki i rzadkość podawaj WYŁĄCZNIE przy wiarygodnych podstawach. Nie wymyślaj katalogu. Confidence całej analizy nigdy nie może wynosić 100%. Odpowiadaj po polsku.`},{type:"input_image",image_url:images[0],detail:"high"},{type:"input_image",image_url:images[1],detail:"high"}];
  const feature={type:"object",additionalProperties:false,properties:{value:{type:"string"},confidence:{type:"integer",minimum:0,maximum:100},method:{type:"string",enum:["visual_observation","relative_geometry","legend_reading","not_observable"]},note:{type:"string"}},required:["value","confidence","method","note"]};
  const fpProps={}; for(const k of ["punctuationPattern","dateSpacing","datePosition","legendStartClock","legendEndClock","portraitOrientation","crownShape","shieldPosition","mintMarkPosition","eagleTail","wingPattern","featherPattern","letterForms","digitForms","monogramShape","edgeFeature"]) fpProps[k]=feature;
  const schema={type:"object",additionalProperties:false,properties:{variant:{type:"string"},kopickiReference:{type:"string"},kopickiRarity:{type:"string"},obverseDetails:{type:"string"},reverseDetails:{type:"string"},legendPunctuation:{type:"string"},diagnosticFeatures:{type:"array",items:{type:"string"}},fingerprint:{type:"object",additionalProperties:false,properties:{version:{type:"integer",enum:[1]},side:{type:"string",enum:["both"]},quality:{type:"string",enum:["observed","limited"]},source:{type:"string",enum:["user_photo"]},features:{type:"object",additionalProperties:false,properties:fpProps,required:Object.keys(fpProps)}},required:["version","side","quality","source","features"]},fullDescription:{type:"string"},confidence:{type:"integer",minimum:0,maximum:95},warnings:{type:"array",items:{type:"string"}}},required:["variant","kopickiReference","kopickiRarity","obverseDetails","reverseDetails","legendPunctuation","diagnosticFeatures","fingerprint","fullDescription","confidence","warnings"]};
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-5.6",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"coin_detail_v3_fingerprint",strict:true,schema}}})});
  const data=await r.json(); if(!r.ok) return res.status(r.status).json({error:data?.error?.message||"Błąd analizy szczegółowej."});
  let t=data.output_text||""; if(!t&&Array.isArray(data.output)) for(const i of data.output) if(i.type==="message") for(const p of i.content||[]) if(p.type==="output_text") t+=p.text||"";
  const detail=JSON.parse(t); detail.confidence=Math.min(95,Number(detail.confidence)||0); detail.fingerprint={...detail.fingerprint,rights:'owner_photo',createdAt:new Date().toISOString()};
  if(base.userAccepted===true) detail.warnings=[...(detail.warnings||[]),'Opis szczegółowy wygenerowano na podstawie danych zaakceptowanych po korekcie użytkownika.'];
  return res.status(200).json({success:true,detail});
 }catch(e){console.error(e);return res.status(500).json({error:e?.message||"Błąd analizy szczegółowej."});}
}