const ALLOWED_HOSTS=new Set(['wcn.pl','www.wcn.pl']);
const MAX_BYTES=700000,MAX_BATCH=8,DELAY_MS=250;
function text(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function plainField(plain,label,nextLabels=[]){const low=plain.toLowerCase(),needle=(label+':').toLowerCase(),start=low.indexOf(needle);if(start<0)return'';const from=start+needle.length;let end=plain.length;for(const n of nextLabels){const i=low.indexOf((n+':').toLowerCase(),from);if(i>=0&&i<end)end=i}return plain.slice(from,end).trim()}
function parsePrice(v=''){const m=String(v).match(/([0-9][0-9\s.,]*)\s*(zł|PLN|EUR|€|USD|\$)/i);if(!m)return 0;const n=m[1].replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');return Number(n)||0}
function parseDate(v=''){const m=String(v).match(/(\d{2})[-.](\d{2})[-.](\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:''}
function canonical(raw){const u=new URL(String(raw||'').trim());if(u.protocol!=='https:'||!ALLOWED_HOSTS.has(u.hostname.toLowerCase()))throw new Error('Dozwolone są tylko publiczne karty WCN.');const id=(u.pathname.match(/^\/archive\/(\d+)\/?$/)||[])[1];if(!id)throw new Error('Dozwolony jest wyłącznie bezpośredni URL /archive/NUMER.');return `https://wcn.pl/archive/${id}`}
function parseWcn(html,url){const u=new URL(url),id=(u.pathname.match(/^\/archive\/(\d+)\/?$/)||[])[1];const plain=text(html),labels=['Sale','Lot number','Description','Grade','Sell price','Sell date','Cena sprzedaży','Data sprzedaży','Stan','Numer pozycji'];const get=l=>plainField(plain,l,labels.filter(x=>x!==l));const priceRaw=get('Sell price')||get('Cena sprzedaży');const dateRaw=get('Sell date')||get('Data sprzedaży');const grade=get('Grade')||get('Stan');const lot=(get('Lot number')||get('Numer pozycji')||id).match(/\d+/)?.[0]||id;const price=parsePrice(priceRaw),soldAt=parseDate(dateRaw);if(!price||!soldAt)throw new Error('Nie udało się jednoznacznie odczytać ceny i daty sprzedaży.');return{id:`wcn_${lot}`,source:'WCN',sourceId:String(lot),sourceUrl:`https://wcn.pl/archive/${id}`,auctionHouse:'WCN',soldAt,realizedPrice:price,hammerPrice:null,totalPrice:null,price,currency:/€|EUR/i.test(priceRaw)?'EUR':/\$|USD/i.test(priceRaw)?'USD':'PLN',grade:grade.slice(0,24),priceType:'realized',marketFact:true,accessMode:'public_single_record',rightsBasis:'public factual market observation',observedAt:new Date().toISOString()}}
async function fetchOne(raw){const url=canonical(raw),c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'APOMONET/0.1 factual-market-observation; bounded-direct-record-fetch','accept':'text/html'}});if(!r.ok)throw new Error(`Źródło zwróciło HTTP ${r.status}.`);const len=Number(r.headers.get('content-length')||0);if(len>MAX_BYTES)throw new Error('Karta źródłowa jest zbyt duża.');const html=await r.text();if(html.length>MAX_BYTES)throw new Error('Karta źródłowa jest zbyt duża.');return parseWcn(html,url)}finally{clearTimeout(timer)}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
module.exports=async function handler(req,res){
  if(req.method==='GET'&&String(req.query?.health||'')==='1')return res.status(200).json({ok:true,adapter:'WCN_DIRECT_RECORDS',allowedHosts:[...ALLOWED_HOSTS],allowedPath:'/archive/{numeric_id}',maxBatch:MAX_BATCH,delayMs:DELAY_MS,storesDescriptions:false,storesImages:false});
  if(!['POST','GET'].includes(req.method))return res.status(405).json({error:'Method not allowed'});
  try{
    if(req.method==='GET'){const fact=await fetchOne(req.query?.url);return res.status(200).json({ok:true,fact,storedFields:['source','sourceId','sourceUrl','auctionHouse','soldAt','realizedPrice','currency','grade','priceType'],discarded:['description','images','layout']})}
    const rawUrls=Array.isArray(req.body?.urls)?req.body.urls:[req.body?.url];const urls=[...new Set(rawUrls.map(x=>String(x||'').trim()).filter(Boolean))];if(!urls.length)return res.status(400).json({error:'Brak URL.'});if(urls.length>MAX_BATCH)return res.status(400).json({error:`Maksymalnie ${MAX_BATCH} bezpośrednich kart WCN w jednym imporcie.`});
    const facts=[],errors=[];for(let i=0;i<urls.length;i++){try{facts.push(await fetchOne(urls[i]))}catch(e){errors.push({url:urls[i],error:e?.name==='AbortError'?'Przekroczono czas pobierania źródła.':String(e?.message||e)})}if(i<urls.length-1)await sleep(DELAY_MS)}
    return res.status(facts.length?200:400).json({ok:facts.length>0,facts,errors,summary:{requested:urls.length,imported:facts.length,failed:errors.length},storedFields:['source','sourceId','sourceUrl','auctionHouse','soldAt','realizedPrice','currency','grade','priceType'],discarded:['description','images','layout']});
  }catch(e){return res.status(400).json({error:e?.name==='AbortError'?'Przekroczono czas pobierania źródła.':String(e?.message||e)})}
}
