const ALLOWED_HOSTS=new Set(['wcn.pl','www.wcn.pl']);
const MAX_BYTES=700000;
function text(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function plainField(plain,label,nextLabels=[]){const low=plain.toLowerCase(),needle=(label+':').toLowerCase(),start=low.indexOf(needle);if(start<0)return'';const from=start+needle.length;let end=plain.length;for(const n of nextLabels){const i=low.indexOf((n+':').toLowerCase(),from);if(i>=0&&i<end)end=i}return plain.slice(from,end).trim()}
function parsePrice(v=''){const m=String(v).match(/([0-9][0-9\s.,]*)\s*(zł|PLN|EUR|€|USD|\$)/i);if(!m)return 0;const n=m[1].replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');return Number(n)||0}
function parseDate(v=''){const m=String(v).match(/(\d{2})[-.](\d{2})[-.](\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:''}
function parseWcn(html,url){const u=new URL(url),id=(u.pathname.match(/^\/archive\/(\d+)\/?$/)||[])[1];if(!id)throw new Error('Dozwolona jest pojedyncza karta WCN /archive/NUMER.');const plain=text(html),labels=['Sale','Lot number','Description','Grade','Sell price','Sell date','Cena sprzedaży','Data sprzedaży','Stan','Numer pozycji'];const get=l=>plainField(plain,l,labels.filter(x=>x!==l));const priceRaw=get('Sell price')||get('Cena sprzedaży');const dateRaw=get('Sell date')||get('Data sprzedaży');const grade=get('Grade')||get('Stan');const lot=(get('Lot number')||get('Numer pozycji')||id).match(/\d+/)?.[0]||id;const price=parsePrice(priceRaw),soldAt=parseDate(dateRaw);if(!price||!soldAt)throw new Error('Nie udało się jednoznacznie odczytać ceny i daty sprzedaży z tej karty WCN.');return{id:`wcn_${lot}`,source:'WCN',sourceId:String(lot),sourceUrl:`https://wcn.pl/archive/${id}`,auctionHouse:'WCN',soldAt,realizedPrice:price,hammerPrice:null,totalPrice:null,price,currency:/€|EUR/i.test(priceRaw)?'EUR':/\$|USD/i.test(priceRaw)?'USD':'PLN',grade:grade.slice(0,24),priceType:'realized',marketFact:true,accessMode:'public_single_record',rightsBasis:'public factual market observation',observedAt:new Date().toISOString()}}
module.exports=async function handler(req,res){
  if(req.method==='GET'&&String(req.query?.health||'')==='1')return res.status(200).json({ok:true,adapter:'WCN_SINGLE_RECORD',allowedHosts:[...ALLOWED_HOSTS],allowedPath:'/archive/{numeric_id}',storesDescriptions:false,storesImages:false});
  if(!['POST','GET'].includes(req.method))return res.status(405).json({error:'Method not allowed'});
  try{
    const raw=String(req.method==='POST'?req.body?.url:req.query?.url||'').trim();if(!raw)return res.status(400).json({error:'Brak URL.'});
    const u=new URL(raw);if(u.protocol!=='https:'||!ALLOWED_HOSTS.has(u.hostname.toLowerCase()))return res.status(400).json({error:'Ten adapter obsługuje obecnie wyłącznie publiczne karty WCN.'});
    if(!/^\/archive\/\d+\/?$/.test(u.pathname))return res.status(400).json({error:'Podaj bezpośredni URL pojedynczej pozycji WCN, np. /archive/344688.'});
    const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);const r=await fetch(u.toString(),{signal:c.signal,redirect:'follow',headers:{'user-agent':'APOMONET/0.1 factual-market-observation; single-record fetch','accept':'text/html'}});clearTimeout(timer);
    if(!r.ok)return res.status(502).json({error:`Źródło zwróciło HTTP ${r.status}.`});const len=Number(r.headers.get('content-length')||0);if(len>MAX_BYTES)return res.status(413).json({error:'Karta źródłowa jest zbyt duża dla kontrolowanego importera.'});
    const html=await r.text();if(html.length>MAX_BYTES)return res.status(413).json({error:'Karta źródłowa jest zbyt duża dla kontrolowanego importera.'});
    return res.status(200).json({ok:true,fact:parseWcn(html,u.toString()),storedFields:['source','sourceId','sourceUrl','auctionHouse','soldAt','realizedPrice','currency','grade','priceType'],discarded:['description','images','layout']});
  }catch(e){return res.status(400).json({error:e?.name==='AbortError'?'Przekroczono czas pobierania źródła.':String(e?.message||e)})}
}
